# Generated by Django 5.2.7 on 2026-05-05 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehaviorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toxic_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('blocked_count', models.PositiveIntegerField(default=0)),
                ('severity_score', models.FloatField(default=0.0)),
                ('warning_level', models.CharField(choices=[('none', 'No Warning'), ('mild', 'Mild (1-2 offences)'), ('moderate', 'Moderate (3-4 offences)'), ('severe', 'Severe (5+ offences)'), ('banned', 'Banned')], default='none', max_length=10)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('first_offence_at', models.DateTimeField(blank=True, null=True)),
                ('last_offence_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-toxic_count'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment')], max_length=10)),
                ('analysed_text', models.TextField(max_length=500)),
                ('toxicity_score', models.FloatField()),
                ('severity', models.FloatField()),
                ('threshold_used', models.FloatField()),
                ('category_scores', models.JSONField(default=dict)),
                ('flagged_labels', models.JSONField(default=list)),
                ('event_type', models.CharField(choices=[('allowed', 'Allowed'), ('warned', 'Warned'), ('blocked', 'Blocked'), ('suspended', 'Suspended')], max_length=10)),
                ('toxic_count_at_event', models.PositiveIntegerField(default=0)),
                ('warning_level_at_event', models.CharField(default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_events', to='posts.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_events', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='toxicity_be_user_id_25fcd6_idx'), models.Index(fields=['event_type', '-created_at'], name='toxicity_be_event_t_ccaff9_idx'), models.Index(fields=['content_type', '-created_at'], name='toxicity_be_content_14e7a9_idx')],
            },
        ),
    ]
