# Generated by Django 5.2.7 on 2026-05-09 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('toxicity_behavior', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbehaviorprofile',
            options={'ordering': ['-psychological_risk_score', '-toxic_count']},
        ),
        migrations.AddField(
            model_name='behaviorevent',
            name='psych_pattern_at_event',
            field=models.CharField(default='one_off', max_length=20),
        ),
        migrations.AddField(
            model_name='behaviorevent',
            name='psych_risk_at_event',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='escalation_risk',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='impulsivity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='malice_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='psychological_pattern',
            field=models.CharField(choices=[('one_off', 'Single Offence'), ('chronic_low', 'Many Low Severity'), ('escalating', 'Increasing Severity'), ('malicious', 'Few High Severity'), ('recovering', 'Improving'), ('impulsive', 'High Frequency Low Severity')], default='one_off', max_length=20),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='psychological_risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='recovery_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='severity_weighted_offenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='weighted_toxicity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='behaviorevent',
            index=models.Index(fields=['psych_pattern_at_event', '-created_at'], name='toxicity_be_psych_p_8e4241_idx'),
        ),
    ]
