# Generated by Django 5.2.9 on 2026-06-28 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('warning', 'Content Warning'), ('blocked', 'Content Blocked'), ('suspended', 'Account Suspended'), ('admin_alert', 'Admin Alert'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('post_like', 'Post Liked'), ('post_comment', 'New Comment'), ('comment_like', 'Comment Liked'), ('comment_reply', 'Comment Reply'), ('video_like', 'Video Liked'), ('video_comment', 'New Video Comment'), ('video_comment_like', 'Video Comment Liked'), ('video_comment_reply', 'Video Comment Reply'), ('content_report', 'Content Reported'), ('system', 'System')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx')],
            },
        ),
    ]
