# Generated by Django 6.0.2 on 2026-05-09 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToxicImageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(help_text='Original filename.', max_length=255)),
                ('score', models.FloatField(help_text='Raw model output score (0.0 – 1.0).')),
                ('label', models.CharField(choices=[('TOXIC', 'Toxic'), ('SAFE', 'Safe')], max_length=10)),
                ('is_toxic', models.BooleanField()),
                ('confidence', models.FloatField(help_text='Confidence percentage.')),
                ('model_used', models.CharField(choices=[('h5', 'MobileNetV2 (.h5)'), ('pkl', 'Keras Pickle (.pkl)')], default='h5', max_length=10)),
                ('threshold', models.FloatField(default=0.5)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who uploaded the image (null if anonymous).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toxicity_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Toxic Image Log',
                'verbose_name_plural': 'Toxic Image Logs',
                'ordering': ['-checked_at'],
            },
        ),
    ]
