# Generated by Django 6.0.2 on 2026-05-10 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('toxicity_image', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageToxicityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post Image'), ('profile', 'Profile Picture'), ('story', 'Story Image'), ('standalone', 'Standalone Check')], default='standalone', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='toxicity_image_scans/')),
                ('is_toxic', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('toxic_probability', models.FloatField(default=0.0)),
                ('non_toxic_probability', models.FloatField(default=0.0)),
                ('model_available', models.BooleanField(default=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('overridden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_toxicity_logs', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_toxicity_logs', to='posts.post')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_image_toxicity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ToxicImageLog',
        ),
        migrations.AddIndex(
            model_name='imagetoxicitylog',
            index=models.Index(fields=['is_toxic', '-created_at'], name='toxicity_im_is_toxi_8f3060_idx'),
        ),
        migrations.AddIndex(
            model_name='imagetoxicitylog',
            index=models.Index(fields=['author', '-created_at'], name='toxicity_im_author__5ddca7_idx'),
        ),
    ]
