# Generated by Django 6.0.2 on 2026-08-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disliked_categories',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='liked_categories',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
