# Generated by Django 5.2.17 on 2026-09-15 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def reconcile_toxicity_tables(apps, schema_editor):
    profile_model = apps.get_model('toxicity_detection', 'UserToxicityProfile')
    log_model = apps.get_model('toxicity_detection', 'ToxicityLog')
    connection = schema_editor.connection
    existing_tables = set(connection.introspection.table_names())

    if profile_model._meta.db_table not in existing_tables:
        schema_editor.create_model(profile_model)

    if log_model._meta.db_table not in existing_tables:
        schema_editor.create_model(log_model)
        return

    existing_columns = {
        column.name for column in connection.introspection.get_table_description(
            connection.cursor(), log_model._meta.db_table
        )
    }
    for field_name in (
        'audio_emotion', 'fusion_result', 'action', 'latent_toxicity'
    ):
        field = log_model._meta.get_field(field_name)
        if field.column not in existing_columns:
            schema_editor.add_field(log_model, field)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    _state_operations = [
        migrations.CreateModel(
            name='UserToxicityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_posts_checked', models.PositiveIntegerField(default=0)),
                ('toxic_post_count', models.PositiveIntegerField(default=0)),
                ('total_comments_checked', models.PositiveIntegerField(default=0)),
                ('toxic_comment_count', models.PositiveIntegerField(default=0)),
                ('highest_toxicity_score', models.FloatField(default=0.0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('last_toxic_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toxicity_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-toxic_post_count'],
            },
        ),
        migrations.CreateModel(
            name='ToxicityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('audio', 'Audio Speech')], max_length=10)),
                ('analysed_text', models.TextField()),
                ('is_toxic', models.BooleanField(default=False)),
                ('max_score', models.FloatField(default=0.0)),
                ('label_scores', models.JSONField(default=dict)),
                ('flagged_labels', models.JSONField(default=list)),
                ('audio_emotion', models.JSONField(blank=True, default=dict)),
                ('fusion_result', models.JSONField(blank=True, default=dict)),
                ('action', models.CharField(default='allow', max_length=40)),
                ('latent_toxicity', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('overridden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toxicity_logs', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toxicity_logs', to='posts.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toxicity_logs', to='posts.post')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_toxicity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_toxic', '-created_at'], name='toxicity_de_is_toxi_45e40b_idx'), models.Index(fields=['author', '-created_at'], name='toxicity_de_author__103217_idx'), models.Index(fields=['content_type', '-created_at'], name='toxicity_de_content_07cce4_idx')],
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=_state_operations,
            database_operations=[
                migrations.RunPython(
                    reconcile_toxicity_tables,
                    migrations.RunPython.noop,
                ),
            ],
        ),
    ]
