# Generated by Django 6.0.4 on 2026-05-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toxicity_detection", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="toxicitylog",
            new_name="toxicity_de_is_toxi_45e40b_idx",
            old_name="toxlog_toxic_date_idx",
        ),
        migrations.RenameIndex(
            model_name="toxicitylog",
            new_name="toxicity_de_author__103217_idx",
            old_name="toxlog_author_date_idx",
        ),
        migrations.RenameIndex(
            model_name="toxicitylog",
            new_name="toxicity_de_content_07cce4_idx",
            old_name="toxlog_ctype_date_idx",
        ),
    ]
